### ISSUE TITLE
Stacktrace from crash when selecting a recording to play.

### ISSUE THREAD

**Issue by tekrantz** [MythTV-Clients/MythtvPlayerForAndroid#1]
```java
02-10 16:54:59.835  32014-32014/org.mythtv.android D/RecordingDetailsActivity﹕ onCreate : enter
02-10 16:54:59.865  32014-32014/org.mythtv.android D/RecordingDetailsActivity﹕ onCreate : creating new RecordingDetailsFragment
02-10 16:54:59.865  32014-32014/org.mythtv.android D/RecordingDetailsActivity﹕ onCreate : exit
02-10 16:54:59.865  32014-32014/org.mythtv.android D/RecordingDetailsFragment﹕ onCreateView : enter
02-10 16:54:59.885  32014-32014/org.mythtv.android W/dalvikvm﹕ Unable to resolve superclass of Lorg/mythtv/android/player/widgets/FloatingActionButton$1; (1547)
02-10 16:54:59.885  32014-32014/org.mythtv.android W/dalvikvm﹕ Link of class 'Lorg/mythtv/android/player/widgets/FloatingActionButton$1;' failed
02-10 16:54:59.885  32014-32014/org.mythtv.android E/dalvikvm﹕ Could not find class 'org.mythtv.android.player.widgets.FloatingActionButton$1', referenced from method org.mythtv.android.player.widgets.FloatingActionButton.<init>
02-10 16:54:59.885  32014-32014/org.mythtv.android W/dalvikvm﹕ VFY: unable to resolve new-instance 5673 (Lorg/mythtv/android/player/widgets/FloatingActionButton$1;) in Lorg/mythtv/android/player/widgets/FloatingActionButton;
02-10 16:54:59.885  32014-32014/org.mythtv.android D/dalvikvm﹕ VFY: replacing opcode 0x22 at 0x0012
02-10 16:54:59.885  32014-32014/org.mythtv.android I/dalvikvm﹕ Could not find method org.mythtv.android.player.widgets.FloatingActionButton.invalidateOutline, referenced from method org.mythtv.android.player.widgets.FloatingActionButton.onSizeChanged
02-10 16:54:59.885  32014-32014/org.mythtv.android W/dalvikvm﹕ VFY: unable to resolve virtual method 49538: Lorg/mythtv/android/player/widgets/FloatingActionButton;.invalidateOutline ()V
02-10 16:54:59.885  32014-32014/org.mythtv.android D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x000e
02-10 16:54:59.895  32014-32014/org.mythtv.android W/dalvikvm﹕ Unable to resolve superclass of Lorg/mythtv/android/player/widgets/FloatingActionButton$1; (1547)
02-10 16:54:59.895  32014-32014/org.mythtv.android W/dalvikvm﹕ Link of class 'Lorg/mythtv/android/player/widgets/FloatingActionButton$1;' failed
02-10 16:54:59.895  32014-32014/org.mythtv.android D/dalvikvm﹕ DexOpt: unable to opt direct call 0xc178 at 0x18 in Lorg/mythtv/android/player/widgets/FloatingActionButton;.<init>
02-10 16:54:59.895  32014-32014/org.mythtv.android D/AndroidRuntime﹕ Shutting down VM
02-10 16:54:59.895  32014-32014/org.mythtv.android W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x4174fda0)
02-10 16:54:59.905  32014-32014/org.mythtv.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.mythtv.android, PID: 32014
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mythtv.android/org.mythtv.android.player.recordings.RecordingDetailsActivity}: android.view.InflateException: Binary XML file line #96: Error inflating class org.mythtv.android.player.widgets.FloatingActionButton
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2334)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
            at android.app.ActivityThread.access$900(ActivityThread.java:169)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5487)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #96: Error inflating class org.mythtv.android.player.widgets.FloatingActionButton
            at android.view.LayoutInflater.createView(LayoutInflater.java:626)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at org.mythtv.android.player.recordings.RecordingDetailsFragment.onCreateView(RecordingDetailsFragment.java:108)
            at android.app.Fragment.performCreateView(Fragment.java:1700)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.BackStackRecord.run(BackStackRecord.java:684)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
            at android.app.Activity.performStart(Activity.java:5460)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
            at android.app.ActivityThread.access$900(ActivityThread.java:169)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5487)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:600)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at org.mythtv.android.player.recordings.RecordingDetailsFragment.onCreateView(RecordingDetailsFragment.java:108)
            at android.app.Fragment.performCreateView(Fragment.java:1700)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.BackStackRecord.run(BackStackRecord.java:684)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
            at android.app.Activity.performStart(Activity.java:5460)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
            at android.app.ActivityThread.access$900(ActivityThread.java:169)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5487)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/fab_background.xml from drawable resource ID #0x7f020035
            at android.content.res.Resources.loadDrawable(Resources.java:3066)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
            at android.view.View.<init>(View.java:3708)
            at android.view.ViewGroup.<init>(ViewGroup.java:480)
            at android.widget.FrameLayout.<init>(FrameLayout.java:101)
            at org.mythtv.android.player.widgets.FloatingActionButton.<init>(FloatingActionButton.java:76)
            at org.mythtv.android.player.widgets.FloatingActionButton.<init>(FloatingActionButton.java:68)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:600)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at org.mythtv.android.player.recordings.RecordingDetailsFragment.onCreateView(RecordingDetailsFragment.java:108)
            at android.app.Fragment.performCreateView(Fragment.java:1700)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.BackStackRecord.run(BackStackRecord.java:684)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
            at android.app.Activity.performStart(Activity.java:5460)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
            at android.app.ActivityThread.access$900(ActivityThread.java:169)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5487)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #6: invalid drawable tag ripple
            at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:986)
            at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:186)
            at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:990)
            at android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
            at android.content.res.Resources.loadDrawable(Resources.java:3062)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
            at android.view.View.<init>(View.java:3708)
            at android.view.ViewGroup.<init>(ViewGroup.java:480)
            at android.widget.FrameLayout.<init>(FrameLayout.java:101)
            at org.mythtv.android.player.widgets.FloatingActionButton.<init>(FloatingActionButton.java:76)
            at org.mythtv.android.player.widgets.FloatingActionButton.<init>(FloatingActionButton.java:68)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:600)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at org.mythtv.android.player.recordings.RecordingDetailsFragment.onCreateView(RecordingDetailsFragment.java:108)
            at android.app.Fragment.performCreateView(Fragment.java:1700)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.BackStackRecord.run(BackStackRecord.java:684)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
            at android.app.Activity.performStart(Activity.java:5460)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
            at android.app.ActivityThread.access$900(ActivityThread.java:169)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5487)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by dmfrey** [comment]
Can you also post the hardware and android version of the device you are
using?

Thanks

**Comment by dmfrey** [comment]
@tekrantz From what I can tell from the stacktrack, you are on 4.x, correct?  Looks like i have a bug in the floating action button on that page to initiate playback. I will get it fixed.

**Comment by tekrantz** [comment]
My device is indeed on 4.x,  4.4.2 to be precise.  It is a galaxy S3 phone.  Alas my Galaxy tab 8.9 is stuck at 4.0.4 which appears to be too old.

**Comment by dmfrey** [comment]
I will take a look and see there is anything in there that won't let me
support 4.0.4.  Sometimes newer libraries remove some functionality and
force a hack for some of those older version.  But I don't see why 4.0
can't be supported.

**Comment by tekrantz** [comment]
I know this is closed.  Just wanted to confirm that it works now on both of my 4.x devices.  Thanks!  Love everything about this app!

**Comment by dmfrey** [comment]
@tekrantz Thanks for your help testing.  Let me know if anything doesn't
work back in the older versions of Android.  I will try to test it out in
an emulator as I go, just to make sure at least ICS+ is covered by this app.

Have you tried any playback?  I would be interested to know your
experiences.

**Comment by tekrantz** [comment]
@tekrantz Thanks for your help testing. Let me know if anything doesn't
work back in the older versions of Android. I will try to test it out in
an emulator as I go, just to make sure at least ICS+ is covered by this app.

Have you tried any playback? I would be interested to know your
experiences.



 

I am having some issues with playback that I will be glad to document as additional “issues” if you are interested.

 

One recording plays back as horizontalish green stripes (I suspect this has something to do with transcoding, not with your app, but I am not sure).

 

I am also getting some “unfortunately MythPlayer has stopped” (that is not a direct quote) when playing a recording while it is still transcoding.  Not sure if it has to do with transcoding messages or playback issues or a combination of doing both at the same time.  I will collect a stack trace as soon as I possibly can.

 

Tim

**Comment by dmfrey** [comment]
For playback issues, I would grab any stack traces and post them as new
issues.  I have seen the green bars as well and have not found out what is
causing that at this point either.

Bill has posted a way to turn on logging on the backend for the
mythtranscode process.  Unfortunately, that is out of my area to diagnose
what the problem is.  What you can check on those recordings if it is also
happening in mythweb:6544.  Install the jwplayer plugin and see if that
also displays the green bars.  If it does, then it is the backend that is
causing that (that is my speculation as well).  For any stream, see if it
plays in the jwplayer.  I will gladly look at any resulting stack traces in
the app to see if there is something I can do there as well.

Unfortunately, I do not feel mythtranscode is able to fully process all
filetypes yet.  For instance, what will happen if you run a HLS transcode
on an ISO?  I know my bluray MKV files don't produce a playable stream.
And, in myth .27, my hd homerun prime hd recordings don't produce a
playable stream either (all .ts files in the streaming storage group were 0
bytes long).

It gets frustrating on my end.

**Comment by tekrantz** [comment]
Quick note. 

The "green bar" display does indeed happen in mythweb:6544 as well, so certainly a transcode issue.

Second, I am trying to capture a stacktrace for the other issue I mentioned but have decided to take it in steps to try to help with as much info as possible.  I am letting the HLS transcode complete (up to 67 percent so far) then if it does not fail, I will play that entire recording.  If that does not fail I will try to begin a transcode, wait until it gets to > 4 percent complete and begin playing it to see if it will fail.  Certainly looks like the transcode will complete this time.  I will let you know more as I find out more.

Thanks for all your effort.  If my reports/input get to be a PITA let me know, the last thing I want to d is increase your frustration!

FYI, I have PCI tuners for both analog and digital.  I also have a HDHR prime (no cable card...yet) and a HDPVR if there are issues with any of those tuners that you would like me to try to reproduce.

Tim

**Comment by dmfrey** [comment]
Tim,
Your reports won't be a PITA.  I think anything we come across that we can
fix will help to make it a better product.  Please, keep sending them.

I only have HDHomerun Primes (2), so I will be limited in what types of
recordings I can test on.  I know Bill also has a few different tuners as
well.  The more types we can capture, the more we can account for.

Dan
