### ISSUE TITLE
IllegalStateException from Select Default Recording Group

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#100]
Go to Settings, Recording Settings, Enable Default Recording Group,
toggle it on, Select Default Recording Group and the following fires:
```
03-16 22:37:25.905 17670-17670/org.mythtv.android V/AppRecordingSettingsFragment: onCreate : enter
03-16 22:37:25.909 17670-17670/org.mythtv.android V/AppRecordingSettingsFragment: onCreate : exit
03-16 22:37:26.174 17670-17687/org.mythtv.android D/OpenGLRenderer: endAllStagingAnimators on 0xa05f6100 (RippleDrawable) with handle 0xb073a120
03-16 22:37:31.345 17670-17670/org.mythtv.android D/AndroidRuntime: Shutting down VM
03-16 22:37:31.348 17670-17670/org.mythtv.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: org.mythtv.android, PID: 17670
                                                                    java.lang.IllegalStateException: ListPreference requires an entries array and an entryValues array.
                                                                        at android.preference.ListPreference.onPrepareDialogBuilder(ListPreference.java:249)
                                                                        at android.preference.DialogPreference.showDialog(DialogPreference.java:306)
                                                                        at android.preference.DialogPreference.onClick(DialogPreference.java:277)
                                                                        at android.preference.Preference.performClick(Preference.java:994)
                                                                        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
                                                                        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                        at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                                                                        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
                                                                        at android.widget.AbsListView$3.run(AbsListView.java:3903)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by dmfrey** [comment]
I forgot about the recording groups. I am gonna have to do some work get that implemented. I am considering disabling this feature for now. I don't want to hold up release on it. Thoughts?

**Comment by billmeek** [comment]
I agree, I'm thinking of a new endpoint that retrieves a list of
recgroups with passwords, e.g. Dvr/GetRecGroups that pulls
this:
```sql
mysql> SELECT recgroup,displayname,password,special FROM recgroups WHERE special = 0;
+----------+----------------+----------+---------+
| recgroup | displayname    | password | special |
+----------+----------------+----------+---------+
| TOH      | This Old House | hot      |       0 |
+----------+----------------+----------+---------+
```

Would that be of value to the app? It could allow Dvr/GetTitleInfoList etc.
to return only un-password protected groups unless a new parameter
was supplied like GroupPassword=hot.

**Comment by dmfrey** [comment]
yes, i think so. otherwise, I need to determine it from the data downloaded.
