### ISSUE TITLE
Loading Videos from cache periodically causes App Crash after cache expired

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#108]
Branch: https://github.com/MythTV-Clients/MythtvPlayerForAndroid/tree/bugfix/issue_108_fix_load_from_cache

```java
03-23 22:04:41.750 10760-10760/org.mythtv.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: org.mythtv.android, PID: 10760
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'rx.Observable rx.Observable.doOnNext(rx.functions.Action1)' on a null object reference
                                                                        at org.mythtv.android.data.repository.datasource.DiskVideoDataStore.getCategory(DiskVideoDataStore.java:39)
                                                                        at org.mythtv.android.data.repository.VideoDataRepository.getVideoSeriesListByContentType(VideoDataRepository.java:75)
                                                                        at org.mythtv.android.domain.interactor.GetVideoSeriesCategoryContentTypeList.buildUseCaseObservable(GetVideoSeriesCategoryContentTypeList.java:31)
                                                                        at org.mythtv.android.domain.interactor.UseCase.execute(UseCase.java:42)
                                                                        at org.mythtv.android.presentation.presenter.TelevisionSeriesCategoryListPresenter.getTelevisionSeriesCategoryList(TelevisionSeriesCategoryListPresenter.java:123)
                                                                        at org.mythtv.android.presentation.presenter.TelevisionSeriesCategoryListPresenter.loadTelevisionSeriesCategoryList(TelevisionSeriesCategoryListPresenter.java:81)
                                                                        at org.mythtv.android.presentation.presenter.TelevisionSeriesCategoryListPresenter.initialize(TelevisionSeriesCategoryListPresenter.java:69)
                                                                        at org.mythtv.android.presentation.view.fragment.AppTelevisionListFragment.loadTelevisionList(AppTelevisionListFragment.java:247)
                                                                        at org.mythtv.android.presentation.view.fragment.AppTelevisionListFragment.onActivityCreated(AppTelevisionListFragment.java:87)
                                                                        at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1983)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                        at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:164)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                                                                        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
                                                                        at android.view.View.measure(View.java:18794)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:664)
                                                                        at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:731)
                                                                        at android.view.View.measure(View.java:18794)
                                                                        at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1075)
                                                                        at android.view.View.measure(View.java:18794)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                        at android.view.View.measure(View.java:18794)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                        at android.view.View.measure(View.java:18794)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at android.view.View.measure(View.java:18794)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                        at android.view.View.measure(View.java:18794)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                        at android.view.View.measure(View.java:18794)
                                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                                    	at android.view.ViewRootImpl.measureHierarchy(ViewRoo
```

**Comment by dmfrey** [comment]
@billmeek Use the branch in this issue and see if you can reproduce the bug where loading videos fail, usually after cache has expired, every other day or so

**Comment by billmeek** [comment]
Worked fine this morning. I switched back to develop and will
watch for it tomorrow.

**Comment by billmeek** [comment]
@dmfrey, just got another one:

Branch: develop, Tag: mythtv-player-2.0.1-dirty, Commit: 9e1805c

I have the full stack if needed.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'rx.Observable rx.Observable.doOnNext(rx.functions.Action1)' on a null object reference
```

**Comment by dmfrey** [comment]
@billmeek can you post the full stacktrace here?

**Comment by billmeek** [comment]
To be clear, this was a regression test and was back on
the develop branch, so the fix above wasn't included.
```
03-28 21:13:46.218 876-876/org.mythtv.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: org.mythtv.android, PID: 876
                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'rx.Observable rx.Observable.doOnNext(rx.functions.Action1)' on a null object reference
                                                                    at org.mythtv.android.data.repository.datasource.DiskVideoDataStore.getCategory(DiskVideoDataStore.java:39)
                                                                    at org.mythtv.android.data.repository.VideoDataRepository.getVideoSeriesListByContentType(VideoDataRepository.java:75)
                                                                    at org.mythtv.android.domain.interactor.GetVideoSeriesCategoryContentTypeList.buildUseCaseObservable(GetVideoSeriesCategoryContentTypeList.java:31)
                                                                    at org.mythtv.android.domain.interactor.UseCase.execute(UseCase.java:42)
                                                                    at org.mythtv.android.presentation.presenter.TelevisionSeriesCategoryListPresenter.getTelevisionSeriesCategoryList(TelevisionSeriesCategoryListPresenter.java:123)
                                                                    at org.mythtv.android.presentation.presenter.TelevisionSeriesCategoryListPresenter.loadTelevisionSeriesCategoryList(TelevisionSeriesCategoryListPresenter.java:81)
                                                                    at org.mythtv.android.presentation.presenter.TelevisionSeriesCategoryListPresenter.initialize(TelevisionSeriesCategoryListPresenter.java:69)
                                                                    at org.mythtv.android.presentation.view.fragment.AppTelevisionListFragment.loadTelevisionList(AppTelevisionListFragment.java:247)
                                                                    at org.mythtv.android.presentation.view.fragment.AppTelevisionListFragment.onActivityCreated(AppTelevisionListFragment.java:87)
                                                                    at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1983)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                    at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                    at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:164)
                                                                    at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                                    at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                                                                    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                    at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:664)
                                                                    at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:731)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1071)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                                    at android.view.ViewRootImpl.measureHierarchy(ViewRootI

```

**Comment by dmfrey** [comment]
Ok, this is what I figured. It is the same issue that was fixed in the
branch.
