### ISSUE TITLE
Amazon FireTV does not support Google Voice Search

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#186]
Reported by @dekarl 

I tried with the APK from github releases with the following result
when trying to search in the recordings screen.
Looks like com.google.android.voicesearch is missing from FireOS...
(according to
http://stackoverflow.com/questions/9479846/no-activity-found-to-handle-intent-act-android-speech-action-recognize-speech
)
But even that app is not available in my country, yet.
Looks like the missing speech to text activity is not handled, yet?
"NOTE: There may not be any applications installed to handle this
action, so you should make sure to catch ActivityNotFoundException."

```
I/ActivityManager( 1832): START u0
{act=android.speech.action.RECOGNIZE_SPEECH (has extras)} from uid 10015
on display 0
D/AndroidRuntime(10607): Shutting down VM
E/AndroidRuntime(10607): FATAL EXCEPTION: main
E/AndroidRuntime(10607): Process: org.mythtv.android, PID: 10607
E/AndroidRuntime(10607): android.content.ActivityNotFoundException: No
Activity found to handle Intent {act=android.speech.action.RECOGNIZE_SPEECH (has extras) }
E/AndroidRuntime(10607):        at
android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1797)
E/AndroidRuntime(10607):        at 
android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
E/AndroidRuntime(10607):        at
android.app.Activity.startActivityForResult(Activity.java:3771)
E/AndroidRuntime(10607):        at
android.app.Activity.startActivityForResult(Activity.java:3732)
E/AndroidRuntime(10607):        at
org.mythtv.android.view.activity.tv.SearchableActivity$1.recognizeSpeech(SearchableActivity.java:145)
E/AndroidRuntime(10607):        at
android.support.v17.leanback.widget.SearchBar.startRecognition(SearchBar.java:554)
E/AndroidRuntime(10607):        at
android.support.v17.leanback.app.SearchFragment$4.run(SearchFragment.java:194)
E/AndroidRuntime(10607):        at
android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(10607):        at
android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(10607):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(10607):        at
android.app.ActivityThread.main(ActivityThread.java:5466)
E/AndroidRuntime(10607):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10607):        at
java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(10607):        at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
E/AndroidRuntime(10607):        at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
I/AndroidRuntime(10607): To Report FATAL to activityManagerService
I/ActivityManager( 1832): handleApplicationCrash
W/ActivityManager( 1832):   Force finishing activity 1
org.mythtv.android/.view.activity.tv.SearchableActivity
I/ActivityManager( 1832): addErrorToDropBox inserted
hashcode=558234d2102138a369448751c2d68515a627a295 for eventType crash.
I/Vlog    ( 1832):
3p:fg_crash:fgtracking=true;DV;1,key=org.mythtv.android;DV;1,Counter=1.0;CT;1,unit=count;DV;1,metadata=558234d2102138a369448751c2d68515a627a295;DV;1:HI
I/ActivityManager( 1832): Next activity is on the same task, skipping
moveHomeStackTaskToTop()
I/Process (10607): Sending signal. PID: 10607 SIG: 9
I/AndroidRuntime(10607): Finished reporting FATAL to activityManagerService
I/CrashDescriptorUtil( 1832): addErrorToCommonLog Hash already present
in file
I/WindowState( 1832): WIN DEATH: Window{1c90a472 u0
org.mythtv.android/org.mythtv.android.view.activity.tv.RecordingsActivity}
I/WindowState( 1832): WIN DEATH: Window{311c5458 u0
org.mythtv.android/org.mythtv.android.view.activity.tv.SearchableActivity}
I/ActivityManager( 1832): Process org.mythtv.android (pid 10607) has died
W/art     (  746): PreZygoteFork called when we already have a zygote space.
V/WindowManager( 1832): Adding window Window{1fe4850f u0 Starting
org.mythtv.android} at 12 of 15 (before Window{311c5458 u0
org.mythtv.android/org.mythtv.android.view.activity.tv.SearchableActivity EXITING})
I/ActivityManager( 1832): Start proc 10777:org.mythtv.android/u0a15 for
activity org.mythtv.android/.view.activity.tv.RecordingsActivity
```

**Comment by dekarl** [comment]
A small addition, https://play.google.com/store/apps/details?id=com.google.android.voicesearch just states "This content is not available in your country yet.", so its not just FireTV.

**Comment by dmfrey** [comment]
@dekarl this should fix it. I'm away on business, so I can't test it myself at this time. If you can pull it and try it out, let me know.

**Comment by dmfrey** [comment]
@dekarl have you been able to verify this with the current develop branch?

**Comment by dmfrey** [comment]
@dekarl Amazon has now addressed this in their documentation.  It can be found here

    (Avoiding Speech Recognition Errors from Leanback)[https://developer.amazon.com/public/solutions/devices/fire-tv/docs/implementing-search-fire-tv#avoiding-speech-recognition-errors-from-leanback]

This is going into release 3.0.2.  Can you get the beta release on the FireTV?
