### ISSUE TITLE
Skip programs with no starttime

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#24]
```java
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long org.joda.time.DateTime.getMillis()' on a null object reference
at org.mythtv.android.library.persistence.service.dvr.DvrPersistenceServiceEventHandler.updateRecordedPrograms(DvrPersistenceServiceEventHandler.java:223)
at org.mythtv.android.library.core.service.v028.dvr.DvrServiceV28EventHandler.updateRecordedPrograms(DvrServiceV28EventHandler.java:92)
at org.mythtv.android.library.core.utils.RefreshRecordedProgramsTask.doInBackground(RefreshRecordedProgramsTask.java:43)
at org.mythtv.android.library.core.utils.RefreshRecordedProgramsTask.doInBackground(RefreshRecordedProgramsTask.java:12)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

Google Play Console error

**Comment by dmfrey** [comment]
Seems to be an issue with null end times as well

**Comment by dmfrey** [comment]
Affecting Recording Start and Ends

Reported on Google Play Console

**Comment by fphillips** [comment]
I share my recorded json dump with your gmail addy, Daniel. Look for an email for google drive.

**Comment by dmfrey** [comment]
Thank you @fpillips

**Comment by dmfrey** [comment]
@fpillips In firefox, install the JSONView extension and then open the file you sent me.  It should be formatted for clearer reading.  The very first Program entry has a lot of fields that are all empty. I have been going through the list, but that seems to be the only one i have found so far.

**Comment by fphillips** [comment]
Yeah, I had seen the one for 0_00000000000000_00000000000000.nuv. It has an empty title/subtitle, notably. I was thinking from discussions way back this was some sort of default and expected or innocuous, but maybe not. I'll see if I can find any reference to where it came from.

**Comment by dmfrey** [comment]
Are you in the beta on the Google+ community? If so, I can do a quick build
of 1.1.6, which has the fix for this (missing recording start and end ts,
as well as already doing program start and end ts, etc.) and push it to the
beta channel.  Then, it should come down to your phone.  You can try it out
and it should just dump this one entry.  Then you won't have to do anything
on your end.

Does this recording break anything on any of your frontends?

**Comment by fphillips** [comment]
Not in the beta, but I can be. I haven't seen any problems on linux frontends that would make me think is related. The old android mythtv frontend stopped working a year or two ago, but I remember seeing this nuv entry much longer before that. I'm pretty sure it was inserted when I recreated my database in 2009, circa 0.21.

**Comment by dmfrey** [comment]
version 1.1.6 has been published to the beta channel.  It will be available in an hour or so.  Go to the G+ Community and accept the beta link.  When it is available, it should just come down like any other public version.

**Comment by fphillips** [comment]
I had been trying the beta program link and getting an error page, waiting and thinking that the build wasn't available yet. Finally saw the 'join community' button at the top - that's what I was missing. Didn't want to wait for it to auto-update, so I force-stopped the play store app and it saw the update and soon as I went back into the play store. It works now.

**Comment by dmfrey** [comment]
That's great. Let me know if you are missing any recorded programs. I will
try to diagnose the json further to try to find whatever is missing.

**Comment by fphillips** [comment]
I have four recgroups: Default, Live TV, Movie, and Sitcom. When I exclude Live TV, there are 855 entries. The app shows 854, so it is only excluding the nuv, as expected.
