### ISSUE TITLE
Black Preview Causes Near White On White Text

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#28]
Running on issue_26.

![blackimageunreadabletext_2015-04-03-18-16-05](https://cloud.githubusercontent.com/assets/1831699/6994431/25caf79a-dadf-11e4-87d5-40d7c5b62777.jpg)

**Comment by dmfrey** [comment]
@billmeek I don't have any recordings that show like this.  It should be pulling text color as well from the palette derived from the image as well.  Try this out on my next commit.

**Comment by billmeek** [comment]
Running on mythtvplayer-1.1-beta-2-23-g886e40e. Now getting
Unfortunately, Mythtv Player has stopped.

```
04-04 21:14:03.160  15962-15962/org.mythtv.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalArgumentException: background can not be translucent
            at android.support.v7.graphics.ColorUtils.findMinimumAlpha(ColorUtils.java:90)
            at android.support.v7.graphics.ColorUtils.getTextColorForBackground(ColorUtils.java:127)
            at android.support.v7.graphics.Palette$Swatch.ensureTextColorsGenerated(Palette.java:621)
            at android.support.v7.graphics.Palette$Swatch.getTitleTextColor(Palette.java:605)
            at org.mythtv.android.player.app.recordings.RecordingDetailsFragment$2.onSuccess(RecordingDetailsFragment.java:241)
            at com.squareup.picasso.ImageViewAction.complete(ImageViewAction.java:51)
            at com.squareup.picasso.Picasso.deliverAction(Picasso.java:557)
            at com.squareup.picasso.Picasso.complete(Picasso.java:509)
            at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:116)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4507)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by dmfrey** [comment]
@billmeek I am capturing that process for an exception. if one is thrown it will default back to colors in the colors.xml
