### ISSUE TITLE
Developer Console: Null Pointer In RecordingPlayerActivity.onCreate (RecordingPlayerActivity.java:50)

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#47]
I deleted/disabled VLC/Player and tried to duplicate this on my
Nexus 7 running: 5.0.2. Android picked some other player although
it took a long time to start and couldn't play the video.

```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mythtv.android/org.mythtv.android.player.app.player.RecordingPlayerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int)' on a null object reference
at org.mythtv.android.player.app.player.RecordingPlayerActivity.onCreate(RecordingPlayerActivity.java:50)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
```

**Comment by dmfrey** [comment]
Why was the mFileUrl null?  Looks like something didn't get passed in correctly from the previous Activity/Fragment

**Comment by dmfrey** [comment]
Were you able to attempt to play the video before it was 2% ready on the backend?

**Comment by billmeek** [comment]
I've not been able to duplicate this.

The "Play" button didn't appear before there was a stream to decode. I
was monitoring the livestream table on the BE and it was 15 before the
button showed up.

**Comment by dmfrey** [comment]
Does the livestream record in the sqlitedb contains the file url?

**Comment by billmeek** [comment]
All of mine have the relative_url and none have the full_url.

Without knowing who submitted the Developer Console entry,
and without being able to duplicate the error, I'm not sure what
else to do.

Would it be acceptable to just check for null, print a Log.e and
return?
