### ISSUE TITLE
Fatal Exception: NullPointerException Fired When Trying To Leave Watch Videos Screen

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#56]
Can't recreate, seen 1 time on a 4.0.4 tablet.

```
04-27 18:19:39.884    2305-4707/org.mythtv.android V/VideosAsyncTaskLoader﹕ loadInBackground : video iteration
04-27 18:19:39.884    2305-4707/org.mythtv.android V/VideosAsyncTaskLoader﹕ loadInBackground : exit
04-27 18:19:39.954    2305-2305/org.mythtv.android D/AndroidRuntime﹕ Shutting down VM
04-27 18:19:39.954    2305-2305/org.mythtv.android W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40c5a1f8)
04-27 18:19:39.984    2305-2305/org.mythtv.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at org.mythtv.android.player.app.videos.MovieDetailsFragment$2.onError(MovieDetailsFragment.java:270)
            at com.squareup.picasso.ImageViewAction.error(ImageViewAction.java:67)
            at com.squareup.picasso.Picasso.deliverAction(Picasso.java:563)
            at com.squareup.picasso.Picasso.complete(Picasso.java:510)
            at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:117)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4507)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by dmfrey** [comment]
closes #56

this class no longer exists
