### ISSUE TITLE
Developer Console: NumberFormatException: Invalid int: "", App version 1.1.9

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#67]
No user comment. 

    Application version   1.1.9
    Android 4.4
    Galaxy Tab2 10.1 (espresso10wifi)
```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NumberFormatException: Invalid int: ""
at java.lang.Integer.invalidInt(Integer.java:137)
at java.lang.Integer.parseInt(Integer.java:358)
at java.lang.Integer.parseInt(Integer.java:331)
at org.mythtv.android.library.core.MainApplication$ServerVersionAsyncTask.doInBackground(MainApplication.java:256)
at org.mythtv.android.library.core.MainApplication$ServerVersionAsyncTask.doInBackground(MainApplication.java:246)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

**Comment by dmfrey** [comment]
stacktrace does not line up with current code, however, I think i found where this NullPointerException might be firing.  Fix should resolve it.  Unsure how to test this resolution, however.
