### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#92]
This fired after updating from Android Studio. Starting the app
again ran without the exception. Nexus 7 running
Android 6.0.1 at commit 4aa67ee. I've seen this before, so
it's not this commit. Just haven't caught the trace before.

```
01-26 13:01:39.308 2259-2259/org.mythtv.android I/ProgramModelDataMapper: transform : program=Program(id=0, startTime=2016-01-25T19:00:00.000Z, endTime=2016-01-25T20:00:00.000Z, title=The Dr. Oz Show, subTitle=Could You Have a Parasite and Not Even Know It?, category=Talk, catType=series, repeat=false, videoProps=11, audioProps=1, subProps=1, seriesId=EP01172991, programId=EP011729911312, stars=0.0, fileSize=6685634380, lastModified=2016-01-25T20:03:23.000Z, programFlags=5, fileName=1321_20160125190000.ts, hostName=mc0, airdate=null, description=What to do if one has a parasite; the self-proclaimed ``fat dad and fat kid'' take control of their health; singer Brandy discusses her health., inetref=ttvdb.py_123401, season=0, episode=0, totalEpisodes=0, channel=ChannelInfo(chanId=1321, chanNum=32_1, callSign=WFLD, iconURL=/Guide/GetChannelIcon?ChanId=1321, channelName=WFLD, mplexId=7, serviceId=3, aTSCMajorChan=32, aTSCMinorChan=1, format=ATSC, frequencyId=31, fineTune=0, chanFilters=, sourceId=1, inputId=0, commFree=false, useEIT=false, visible=true, xMLTVID=20361, defaultAuth=, programs=null), recording=RecordingInfo(recordedId=5237, status=-3, priority=0, startTs=2016-01-25T19:00:00.000Z, endTs=2016-01-25T20:00:01.000Z, recordId=388, recGroup=Default, playGroup=Default, storageGroup=Default, recType=0, dupInType=15, dupMethod=6, encoderId=0, encoderName=, profile=Default), artworkInfos=[ArtworkInfo(url=/Content/GetImageFile?StorageGroup=Coverart&FileName=/The Dr. Oz Show Season 6_coverart.jpg, fileName=myth://Coverart@mc0/The Dr. Oz Show Season 6_coverart.jpg, storageGroup=Coverart, type=coverart), ArtworkInfo(url=/Content/GetImageFile?StorageGroup=Fanart&FileName=/The Dr. Oz Show Season 6_fanart.jpg, fileName=myth://Fanart@mc0/The Dr. Oz Show Season 6_fanart.jpg, storageGroup=Fanart, type=fanart), ArtworkInfo(url=/Content/GetImageFile?StorageGroup=Banners&FileName=/oz_banner.jpg, fileName=myth://Banners@mc0/oz_banner.jpg, storageGroup=Banners, type=banner)], castMembers=[CastMember(name=Dr. Mehmet Oz, characterName=, role=host, translatedRole=Host), CastMember(name=Brandy, characterName=, role=guest, translatedRole=Guest)], liveStreamInfo=null)
01-26 13:01:39.309 2259-2259/org.mythtv.android I/ProgramModelDataMapper: transform : recordingInfo=RecordingInfo(recordedId=5237, status=-3, priority=0, startTs=2016-01-25T19:00:00.000Z, endTs=2016-01-25T20:00:01.000Z, recordId=388, recGroup=Default, playGroup=Default, storageGroup=Default, recType=0, dupInType=15, dupMethod=6, encoderId=0, encoderName=, profile=Default)
01-26 13:01:39.310 2259-2259/org.mythtv.android I/ProgramModelDataMapper:  transform : programModel.getRecording=RecordingInfoModel(recordedId=388, status=-3, priority=0, startTs=2016-01-25T19:00:00.000Z, endTs=2016-01-25T20:00:01.000Z, recordId=null, recGroup=Default, playGroup=Default, storageGroup=Default, recType=0, dupInType=15, dupMethod=6, encoderId=0, encoderName=, profile=Default)
01-26 13:01:39.312 2259-2259/org.mythtv.android I/ProgramModelDataMapper: transform : program=Program(id=0, startTime=2016-01-25T15:00:00.000Z, endTime=2016-01-25T15:30:00.000Z, title=This Old House, subTitle=This Old Tree House, category=Home improvement, catType=series, repeat=false, videoProps=34, audioProps=1, subProps=1, seriesId=EP00004444, programId=EP000044440903, stars=0.0, fileSize=798555568, lastModified=2016-01-25T15:31:35.000Z, programFlags=5, fileName=1113_20160125150000.ts, hostName=mc0, airdate=null, description=Arched shingle design for the front porch gable; custom floor cloth for the kitchen; porch railings; treehouse., inetref=ttvdb.py_77444, season=0, episode=0, totalEpisodes=0, channel=ChannelInfo(chanId=1113, chanNum=11_3, callSign=WTTW-SD, iconURL=/Guide/GetChannelIcon?ChanId=1113, channelName=WTTW-DT, mplexId=13, serviceId=5, aTSCMajorChan=11, aTSCMinorChan=3, format=ATSC, frequencyId=47, fineTune=0, chanFilters=, sourceId=1, inputId=0, commFree=false, useEIT=false, visible=true, xMLTVID=49346, defaultAuth=, programs=null), recording=RecordingInfo(recordedId=5236, status=-3, priority=1, startTs=2016-01-25T15:00:00.000Z, endTs=2016-01-25T15:30:00.000Z, recordId=408, recGroup=TOH, playGroup=Default, storageGroup=Default, recType=0, dupInType=15, dupMethod=6, encoderId=0, encoderName=, profile=Default), artworkInfos=[ArtworkInfo(url=/Content/GetImageFile?StorageGroup=Coverart&FileName=/This Old House Season 36_coverart.jpg, fileName=myth://Coverart@mc0/This Old House Season 36_coverart.jpg, storageGroup=Coverart, type=coverart), ArtworkInfo(url=/Content/GetImageFile?StorageGroup=Fanart&FileName=/This Old House Season 36_fanart.jpg, fileName=myth://Fanart@mc0/This Old House Season 36_fanart.jpg, storageGroup=Fanart, type=fanart), ArtworkInfo(url=/Content/GetImageFile?StorageGroup=Banners&FileName=/This Old House Season 36_banner.jpg, fileName=myth://Banners@mc0/This Old House Season 36_banner.jpg, storageGroup=Banners, type=banner)], castMembers=[CastMember(name=Kevin O'Connor, characterName=, role=host, translatedRole=Host)], liveStreamInfo=null)
01-26 13:01:39.313 2259-2259/org.mythtv.android I/ProgramModelDataMapper: transform : recordingInfo=RecordingInfo(recordedId=5236, status=-3, priority=1, startTs=2016-01-25T15:00:00.000Z, endTs=2016-01-25T15:30:00.000Z, recordId=408, recGroup=TOH, playGroup=Default, storageGroup=Default, recType=0, dupInType=15, dupMethod=6, encoderId=0, encoderName=, profile=Default)
01-26 13:01:39.314 2259-2259/org.mythtv.android I/ProgramModelDataMapper:  transform : programModel.getRecording=RecordingInfoModel(recordedId=408, status=-3, priority=1, startTs=2016-01-25T15:00:00.000Z, endTs=2016-01-25T15:30:00.000Z, recordId=null, recGroup=TOH, playGroup=Default, storageGroup=Default, recType=0, dupInType=15, dupMethod=6, encoderId=0, encoderName=, profile=Default)
01-26 13:01:39.403 2259-3433/org.mythtv.android E/AndroidRuntime: FATAL EXCEPTION: Thread-763
                                                                  Process: org.mythtv.android, PID: 2259
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
                                                                      at org.mythtv.android.presentation.view.component.AutoLoadImageView$DiskCache.put(AutoLoadImageView.java:431)
                                                                      at org.mythtv.android.presentation.view.component.AutoLoadImageView.cacheBitmap(AutoLoadImageView.java:273)
                                                                      at org.mythtv.android.presentation.view.component.AutoLoadImageView.access$500(AutoLoadImageView.java:30)
                                                                      at org.mythtv.android.presentation.view.component.AutoLoadImageView$1$1.onImageDownloaded(AutoLoadImageView.java:138)
                                                                      at org.mythtv.android.presentation.view.component.AutoLoadImageView$ImageDownloader.download(AutoLoadImageView.java:348)
                                                                      at org.mythtv.android.presentation.view.component.AutoLoadImageView$1.run(AutoLoadImageView.java:132)
```

**Comment by billmeek** [comment]
Just responding to the ideas on IRC: the recording exists and plays
OK in MythTV and on the app. The inetref is good, artwork displays
OK too. Plus, it only fails the 1st time.

In 1st line above: recordingInfo=RecordingInfo(recordedId=5236... which is correct.

But in the 2nd line: programModel.getRecording=RecordingInfoModel(recordedId=408...

And that's wrong, 408 is the recordId. Since this works OK now, it doesn't seem to
be the issue.

**Comment by dmfrey** [comment]
if you get the data from the backend, does it have it in the wrong spot?
Maybe I am mapping it incorrectly.  A lot of things are named the similarly.

**Comment by billmeek** [comment]
I believe the app is doing: http://192.168.1.204:6544/Dvr/GetRecordedList?Descending=true
and the data looks OK to me. If it makes a difference, this program records on 3 different
PBS channels, but I only have one recording of this episode.

Just had another one. I believe I had the verbose level set too high originally,
now it's back at Verbose to get everything. Also note that I added a debug of
my own to prove that the filename was available:
``` java
    synchronized void put( Bitmap bitmap, String fileName ) {

      File file = buildFileFromFilename( fileName );
      if( !file.exists() ) {

        try {
          Log.d(TAG, "WHM DEBUG: filename=" + fileName);
          FileOutputStream fileOutputStream = new FileOutputStream( file );
          bitmap.compress( Bitmap.CompressFormat.PNG, 90, fileOutputStream );
          fileOutputStream.flush();
          fileOutputStream.close();

        } catch( IOException e ) {

          Log.e(TAG, e.getMessage());

        }

      }

    }
```

```
01-26 19:13:27.467 7613-29051/org.mythtv.android D/skia: --- SkImageDecoder::Factory returned null
01-26 19:13:27.467 7613-29051/org.mythtv.android D/AutoLoadImageView: download : callback != null
01-26 19:13:27.467 7613-29051/org.mythtv.android D/AutoLoadImageView: loadImageFromUrl.run.onImageDownloaded : enter
01-26 19:13:27.468 7613-29051/org.mythtv.android D/AutoLoadImageView: cacheBitmap : enter
01-26 19:13:27.468 7613-29051/org.mythtv.android D/AutoLoadImageView: cacheBitmap : cache != null
01-26 19:13:27.468 7613-29051/org.mythtv.android D/DiskCache: WHM DEBUG: filename=image_673443735
                                                              
                                                              --------- beginning of crash
01-26 19:13:27.469 7613-29051/org.mythtv.android E/AndroidRuntime: FATAL EXCEPTION: Thread-1045
                                                                   Process: org.mythtv.android, PID: 7613
                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
                                                                       at org.mythtv.android.presentation.view.component.AutoLoadImageView$DiskCache.put(AutoLoadImageView.java:431)
                                                                       at org.mythtv.android.presentation.view.component.AutoLoadImageView.cacheBitmap(AutoLoadImageView.java:273)
                                                                       at org.mythtv.android.presentation.view.component.AutoLoadImageView.access$500(AutoLoadImageView.java:30)
                                                                       at org.mythtv.android.presentation.view.component.AutoLoadImageView$1$1.onImageDownloaded(AutoLoadImageView.java:138)
                                                                       at org.mythtv.android.presentation.view.component.AutoLoadImageView$ImageDownloader.download(AutoLoadImageView.java:348)
                                                                       at org.mythtv.android.presentation.view.component.AutoLoadImageView$1.run(AutoLoadImageView.java:132)
```

**Comment by billmeek** [comment]
With 54ee19e, got the same exception. 1st use of the tablet this
morning. From Home, went to Watch Recordings (which was OK) and
then Watch Videos where this fired:
```
01-27 09:45:52.238 31083-32527/org.mythtv.android D/skia: --- SkImageDecoder::Factory returned null
01-27 09:45:52.238 31083-32527/org.mythtv.android D/AutoLoadImageView: download : callback != null
01-27 09:45:52.238 31083-32527/org.mythtv.android D/AutoLoadImageView: loadImageFromUrl.run.onImageDownloaded : enter
01-27 09:45:52.238 31083-32527/org.mythtv.android D/AutoLoadImageView: cacheBitmap : enter
01-27 09:45:52.238 31083-32527/org.mythtv.android D/AutoLoadImageView: cacheBitmap : cache != null
01-27 09:45:52.239 31083-32527/org.mythtv.android D/DiskCache: WHM DEBUG: filename=image_782878566
                                                               
                                                               --------- beginning of crash
01-27 09:45:52.240 31083-32527/org.mythtv.android E/AndroidRuntime: FATAL EXCEPTION: Thread-1062
                                                                    Process: org.mythtv.android, PID: 31083
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
                                                                        at org.mythtv.android.presentation.view.component.AutoLoadImageView$DiskCache.put(AutoLoadImageView.java:431)
                                                                        at org.mythtv.android.presentation.view.component.AutoLoadImageView.cacheBitmap(AutoLoadImageView.java:273)
                                                                        at org.mythtv.android.presentation.view.component.AutoLoadImageView.access$500(AutoLoadImageView.java:30)
                                                                        at org.mythtv.android.presentation.view.component.AutoLoadImageView$1$1.onImageDownloaded(AutoLoadImageView.java:138)
                                                                        at org.mythtv.android.presentation.view.component.AutoLoadImageView$ImageDownloader.download(AutoLoadImageView.java:348)
                                                                        at org.mythtv.android.presentation.view.component.AutoLoadImageView$1.run(AutoLoadImageView.java:132)
```
When I started the app again, Watch Videos displayed fine. No new videos were added.
The debug statement I added didn't fire on this attempt (and only fired once on the 1st.)

**Comment by billmeek** [comment]
This has the logging added in the above commit and note that this
happens on 1st startup, e.g. on a new day, or new download of the apk.
Frequent, but no 100% of the time:
```
03-11 10:02:39.332 31671-32071/org.mythtv.android D/AutoLoadImageView: download : callback != null
03-11 10:02:39.332 31671-32071/org.mythtv.android D/AutoLoadImageView: loadImageFromUrl.run.onImageDownloaded : enter
03-11 10:02:39.333 31671-32071/org.mythtv.android D/AutoLoadImageView: cacheBitmap : enter
03-11 10:02:39.333 31671-32071/org.mythtv.android D/AutoLoadImageView: cacheBitmap : fileName=image_456519508
03-11 10:02:39.333 31671-32071/org.mythtv.android D/AutoLoadImageView: cacheBitmap : cache != null
03-11 10:02:39.333 31671-32071/org.mythtv.android D/DiskCache: put : fileName=image_456519508
03-11 10:02:39.335 31671-32071/org.mythtv.android E/AndroidRuntime: FATAL EXCEPTION: Thread-448
                                                                    Process: org.mythtv.android, PID: 31671
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
                                                                        at org.mythtv.android.presentation.view.component.AutoLoadImageView$DiskCache.put(AutoLoadImageView.java:434)
                                                                        at org.mythtv.android.presentation.view.component.AutoLoadImageView.cacheBitmap(AutoLoadImageView.java:275)
                                                                        at org.mythtv.android.presentation.view.component.AutoLoadImageView.access$500(AutoLoadImageView.java:30)
                                                                        at org.mythtv.android.presentation.view.component.AutoLoadImageView$1$1.onImageDownloaded(AutoLoadImageView.java:138)
                                                                        at org.mythtv.android.presentation.view.component.AutoLoadImageView$ImageDownloader.download(AutoLoadImageView.java:350)
                                                                        at org.mythtv.android.presentation.view.component.AutoLoadImageView$1.run(AutoLoadImageView.java:132)
```

**Comment by billmeek** [comment]
I added a Log message, just to make any errors stand out, and
(finally) caught some. This happened after a Force Stop/Clear
Cache. Maybe there were more of these in the last few days
and I just missed them because I was looking for a stack trace.

The modified code is this:
``` java
        } catch( NullPointerException | IOException e ) {

          Log.wtf(TAG, "*******************************************************************************************************");
          Log.e( TAG, e.getMessage() );

        }
```
```
03-15 21:51:57.592 30363-30738/org.mythtv.android D/DiskCache: put : fileName=image_563108903
03-15 21:51:57.592 30363-30363/org.mythtv.android D/AutoLoadImageView: loadImageFromUrl : exit
03-15 21:51:57.593 30363-30363/org.mythtv.android D/AutoLoadImageView: setImageUrl : exit
03-15 21:51:57.593 30363-30738/org.mythtv.android E/DiskCache: Just a marker for my testing ********************************************
03-15 21:51:57.595 30363-30742/org.mythtv.android D/AutoLoadImageView: loadImageFromUrl.run : enter
03-15 21:51:57.595 30363-30742/org.mythtv.android D/AutoLoadImageView: getFromCache : enter
03-15 21:51:57.595 30363-30742/org.mythtv.android D/AutoLoadImageView: getFromCache : cache != null
03-15 21:51:57.595 30363-30742/org.mythtv.android D/AutoLoadImageView: getFromCache : exit
03-15 21:51:57.595 30363-30742/org.mythtv.android D/AutoLoadImageView: loadImageFromUrl.run : bitmap == null
03-15 21:51:57.596 30363-30742/org.mythtv.android D/AutoLoadImageView: loadImageFromUrl.run : internet connected
03-15 21:51:57.596 30363-30742/org.mythtv.android D/AutoLoadImageView: download : enter
03-15 21:51:57.609 30363-30737/org.mythtv.android D/skia: --- SkImageDecoder::Factory returned null
03-15 21:51:57.609 30363-30737/org.mythtv.android D/AutoLoadImageView: download : callback != null
03-15 21:51:57.609 30363-30737/org.mythtv.android D/AutoLoadImageView: loadImageFromUrl.run.onImageDownloaded : enter
03-15 21:51:57.609 30363-30737/org.mythtv.android D/AutoLoadImageView: cacheBitmap : enter
03-15 21:51:57.609 30363-30737/org.mythtv.android D/AutoLoadImageView: cacheBitmap : fileName=image_1854741939
03-15 21:51:57.609 30363-30737/org.mythtv.android D/AutoLoadImageView: cacheBitmap : cache != null
03-15 21:51:57.609 30363-30737/org.mythtv.android D/DiskCache: put : fileName=image_1854741939
03-15 21:51:57.610 30363-30737/org.mythtv.android E/DiskCache: Just a marker for my testing ********************************************
03-15 21:51:57.619 30363-30738/org.mythtv.android E/DiskCache: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
03-15 21:51:57.619 30363-30738/org.mythtv.android D/AutoLoadImageView: cacheBitmap : exit
03-15 21:51:57.619 30363-30738/org.mythtv.android D/AutoLoadImageView: loadBitmap : enter
03-15 21:51:57.620 30363-30738/org.mythtv.android D/AutoLoadImageView: loadBitmap : exit
03-15 21:51:57.620 30363-30738/org.mythtv.android D/AutoLoadImageView: loadImageFromUrl.run.onImageDownloaded : exit
03-15 21:51:57.620 30363-30738/org.mythtv.android D/AutoLoadImageView: download : exit
03-15 21:51:57.621 30363-30737/org.mythtv.android E/DiskCache: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
```

**Comment by dmfrey** [comment]
maybe the cache for the images isn't large enough and older ones are getting purged while a process in another thread is trying to access them.  This is probably a concurrency issue.

**Comment by dmfrey** [comment]
With the NullPointerException now being caught, is it causing the app to crash? I see your messages in there for when it fires. What happens in the interface?

**Comment by billmeek** [comment]
No, it doesn't crash \o/, I haven't notices missing images either. On 
occasion, the 1st banner (60 Minutes) is blank and the last (which
has no inetref) inherits a much earlier banner. Can't duplicate this
at will either and refreshing the screen fixes both banners. If it
becomes an problem, I'll open a separate issue.

**Comment by billmeek** [comment]
I keep forgetting about the auto-close on merge. There used to be a
note about that on the screen.

**Comment by dmfrey** [comment]
It will show up. It is because this is in a branch. Once it merges back,
which I think we are good to do, they will all close.
