### ISSUE TITLE
Exception: RuntimeException: Unable to instantiate application com.android.tools.fd.runtime

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#94]
This fires at app startup time. The Home screen never displays. Only the
Unfortunately, Mythtv Player has stopped\nOK message. Running on
commit: a13f450 and a 4.4.2 Android version.
```
01-29 09:03:22.097 4368-4368/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.mythtv.android, PID: 4368
                                                 java.lang.RuntimeException: Unable to instantiate application com.android.tools.fd.runtime.BootstrapApplication: java.lang.ClassNotFoundException: Didn't find class "com.android.tools.fd.runtime.BootstrapApplication" on path: DexPathList[[zip file "/data/app/org.mythtv.android-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.mythtv.android-1, /vendor/lib, /system/lib, /lib]]
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:516)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4690)
                                                     at android.app.ActivityThread.access$1600(ActivityThread.java:172)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1365)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:146)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5598)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.tools.fd.runtime.BootstrapApplication" on path: DexPathList[[zip file "/data/app/org.mythtv.android-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.mythtv.android-1, /vendor/lib, /system/lib, /lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:981)
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4690) 
                                                     at android.app.ActivityThread.access$1600(ActivityThread.java:172) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1365) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:146) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5598) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by dmfrey** [comment]
@billmeek Make sure Android Studio is updated to latest 2.0 preview (5 I
think).

On the CLI, execute ./gradlew wrapper. Make sure it updates Gradle to 2.10.

If neither of these fixes it, disable Instant Run in Android Studio
https://sites.google.com/a/android.com/tools/tech-docs/instant-run

Let me know if this fixes it.

**Comment by billmeek** [comment]
Upgraded to gradle 10 (thought I saw alpha8 load days ago) but it did
appear to [re]install it version, I'm already on AS 2.0 preview 8.

Turning Instant Run off got past the problem.

**Comment by dmfrey** [comment]
Great. The alpha8 is different than gradle 2.10. Alpha8 is the gradle
android plugin.

**Comment by SargeKhan** [comment]
Turning instant run off didn't resolve the issue for me, using gradle 2.0.0

**Comment by dmfrey** [comment]
Make sure you are using the up to date version of Android Studio. @billmeek
and I are both using the Canary channel.  Then rebuild the app. You should
be good after that.

**Comment by dharmeshappzlogic** [comment]
i am using android studio of 2.1.2 version and i have turned instant run off, but not get any success yet. Still facing the same issue.

**Comment by billmeek** [comment]
In Android Studio, have you tried the Build->Clean Project? From the
phone/tablet, Settings->Applications manually  stop, clear data and
remove the app.

If that doesn't help, please comment on your Android version and
if the failure, from LogCat, is the same as the initial one here.

**Comment by ganeshachar** [comment]
Unable to instantiate application com.android.tools.fd.runtime.BootstrapApplication: java.lang.ClassNotFoundException: com.android.tools.fd.runtime.BootstrapApplication(in below lollipop iam facing like this error)


To disable Instant Run, it will work fine follow the below steps to disable instant run
in android studio 
1. Go to File  Settings--> Build,Execution,Deployment -->Instant Run ---> uncheck "Enable instant run"
